const fs = require('fs');
const path = require('path');

const codespaceName = process.env.CODESPACE_NAME;
const base = codespaceName
  ? `https://${codespaceName}-8000.app.github.dev`
  : 'http://localhost:8000';

const outDir = path.join(__dirname, '..', 'octofit-tracker', 'frontend', 'src');
const outFile = path.join(outDir, 'apiConfig.js');

const content = `// Auto-generated by scripts/generate_frontend_api_config.js
export const API_BASE_URL = ${JSON.stringify(base)};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile);
